name: schedule

on:
  schedule:
    # 시간외 단일간 16:00 ~ 18:00
    # KRX 웹은 20분 지연 정보
    # 넉넉하게 18:30 이면 KRX 데이터 확정으로 볼수 있을듯?
    # KST 18:30 = UTC 09:30
    - cron: "30 9 * * *"
  workflow_dispatch: # 수동 실행 가능

jobs:
  schedule:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 9.15.4

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Checkout data branch
        uses: actions/checkout@v4
        with:
          ref: data
          path: data_branch

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
      # ETF 종목의 순자산총액은 다음날이 되어야 나온다. 공휴일이 끼면 날짜 어긋나니까 여유있게 긁는다.
      # 2017년 추석 연휴는 9월 30일부터 10월 9일까지 총 10일간 휴장이었던거 참고
      # KOSPI, KOSDAQ는 당일 데이터로도 문제 없어보임
      - name: date
        run: |
          export TZ="Etc/GMT-9"
          echo "TODAY_KST=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
          echo "YESTERDAY_KST=$(date --date="yesterday" "+%Y-%m-%d")" >> $GITHUB_ENV
          echo "START_DATE=$(date -d "14 days ago" +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "END_DATE=$(date "+%Y-%m-%d")" >> $GITHUB_ENV

      # 과거를 조회하면 기초지수 수치가 조금씩 바뀔수 있다. 이를 피하려고 당일 데이터만 크롤링
      - name: ETF
        run: |
          node cli.ts etf --data-dir ./data_branch/data_ETF --start-date ${TODAY_KST} --end-date ${TODAY_KST} --overwrite

      - name: stock
        run: |
          node cli.ts stock --data-dir ./data_branch/data_KOSPI --start-date ${YESTERDAY_KST} --end-date ${TODAY_KST} --overwrite --market kospi
          node cli.ts stock --data-dir ./data_branch/data_KOSDAQ --start-date ${YESTERDAY_KST} --end-date ${TODAY_KST} --overwrite --market kosdaq

      - name: commit
        run: |
          cd data_branch
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *
          git commit -m "schedule: ${TODAY_KST}" || echo "No changes to commit"
          git push origin data
